config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  resource :authorization, only: %i[new create] do
    get 'email_confirmation/:confirmation_token', action: :email_confirmation, as: :email_confirmation
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :users do
    resources :rewards, only: %i[index]
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      member do
        post :best
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show destroy create update] do
        resources :answers, shallow: true, only: %i[index show destroy create update]
      end
    end
  end

  get 'search', controller: :search, action: :find, as: :search
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  include Linkable

  default_scope { order(id: :asc) }

  has_many :answers, -> { order(best: :desc, id: :asc) }, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_users, through: :subscriptions, source: :user
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :subscribe_author

  private

  def subscribe_author
    Subscription.create!(question: self, user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  expose :questions, -> { Question.all }
  expose :question, scope: -> { Question.with_attached_files }

  def index
    authorize! :index, Question
    render json: questions, each_serializer: BaseQuestionSerializer
  end

  def show
    authorize! :read, question
    render json: question
  end

  def destroy
    authorize! :destroy, question
    question.destroy
  end

  def create
    authorize! :create, Question
    question.user = current_resource_owner
    question.save ? head(:ok) : head(422)
  end

  def update
    authorize! :update, question
    question.update(question_params) ? head(:ok) : head(422)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  after_action :publish_question, only: :create

  expose :questions, -> { Question.all }
  expose :question, scope: -> { Question.with_attached_files }
  expose :answers, from: :question
  expose :answer, -> { Answer.new }
  expose :comment, -> { question.comments.new }

  def show
    authorize! :read, question
    answer.links.new
  end

  def new
    authorize! :create, Question
    question.links.new
    question.build_reward
  end

  def create
    authorize! :create, Question
    question.user = current_user
    if question.save
      redirect_to question, notice: 'Your question successfully created.'
    else
      question.build_reward unless question.reward
      render :new
    end
  end

  def update
    authorize! :update, question
    question.update(question_params)
  end

  def destroy
    authorize! :destroy, question
    question.destroy
    redirect_to questions_path, notice: 'Your question has been deleted.'
  end

  private

  def publish_question
    return if question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      question: question,
      links: question.links,
      files: question.files.map { |file| { id: file.id, name: file.filename.to_s, url: url_for(file) } }
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:id, :name, :url, :_destroy], reward_attributes: [:image, :name])
  end
end

app/views/questions/_question.html.slim
- cache [current_user || 'guest', question] do
  div.question.card.m-3 data-question-id="#{question.id}" id="question-#{question.id}"
    h5.card-header= link_to question.title, question_path(question)
    .card-body
      .question-view-port
        .btn-group.float-right.btn-group-sm
          -if can? :destroy, question
            =link_to 'Delete question', question, method: :delete, class: 'btn btn-danger'
          -if can? :update, question
            =link_to 'Edit', '#', data: { question_id: question.id }, class: 'btn btn-secondary edit-question-link'
          -if can? :create, Subscription
            = render 'subscriptions/subscription', question: question
          -if can? :vote_up, question
            = link_to 'Vote up', vote_up_question_path(question), class: 'votes vote-up btn btn-secondary', method: :post, remote: true
          .votes-count.btn.btn-success.disabled= question.rating
          -if can? :vote_down, question
            = link_to 'Vote down', vote_down_question_path(question), class: 'votes vote-down btn btn-secondary', method: :post, remote: true

        p= question.body

        -if question.files.attached?
          = render 'shared/attachments', attachments: question.files, resource: question

        = render 'shared/links', links: question.links

      = form_with model: question, class: 'hidden question-form', html: { id: "edit-question-#{question.id}" } do |f|
        div.question-errors
          = render 'shared/errors', resource: question
        .field.form-group
          = f.label :title
          = f.text_field :title, class: 'form-control'
        .field.form-group
          = f.label :body
          = f.text_field :body, class: 'form-control'
        .field.form-group
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'
        = render 'shared/links_form', form: f
        = f.submit 'Save', class: 'btn btn-primary'
      = render 'shared/comments', commentable: question

app/views/questions/index.html.slim
.questions
  .questions-wrapper
    = render questions
p= link_to 'Ask question', new_question_path, class: 'btn btn-primary'

app/views/questions/new.html.slim
= form_with model: question, local: true, class: 'm-5' do |f|
  div.question-errors
    = render 'shared/errors', resource: question
  .field.form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .field.form-group
    = f.label :body
    = f.text_field :body, class: 'form-control'
  .field.form-group
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'
  .reward
    h5 Reward:
    = f.fields_for :reward do |r|
      .field.form-group
        = r.label :name
        = r.text_field :name, class: 'form-control'
      .field.form-group
        = r.label :image
        = r.file_field :image, direct_upload: true, class: 'form-control-file'
  = render 'shared/links_form', form: f
  = f.submit 'Ask', class: 'btn btn-primary'

app/views/questions/show.html.slim
.questions-wrapper
  p= render question
.answers.ml-5.m-3
  =render question.answers
- if current_user
  p= render 'answers/form'

app/views/questions/toggle_subscribe.js.erb
$('#question-<%=question.id%> .subscription').html('<%= render 'subscription' %>')

app/views/questions/update.js.erb
$('#question-<%=question.id%> .question-errors').html('<%= render 'shared/errors', resource: question %>');

<%- unless question.errors.present? %>
  $('#question-<%=question.id%>').replaceWith('<%= j render question %>')
<% end %>