config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  resource :authorization, only: %i[new create] do
    get 'email_confirmation/:confirmation_token', action: :email_confirmation, as: :email_confirmation
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :users do
    resources :rewards, only: %i[index]
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      member do
        post :best
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show destroy create update] do
        resources :answers, shallow: true, only: %i[index show destroy create update]
      end
    end
  end

  get 'search', controller: :search, action: :find, as: :search
end

app/views/shared/_attachments.html.slim
.attachments
  h5 Attachments:
  - attachments.each do |attachment|
    - cache [current_user || 'guest', attachment] do
      .file id="attachment-#{attachment.id}"
        = link_to attachment.filename.to_s, url_for(attachment)
        -if can? :destroy, attachment
          = link_to 'Delete attachment', attachment_path(attachment), remote: true, method: :delete, class: 'm-2 btn btn-danger btn-sm'

app/views/shared/_comments.html.slim
h5 Comments:
div.comments data-commentable="#{commentable.class.name.underscore}" data-commentable-id="#{commentable.id}" = render commentable.comments
- if current_user
  = link_to 'Add comment', '#', class: 'add-comment-link', data: { commentable: "#{commentable.class.name.underscore}-#{commentable.id}" }
  = form_with model: [commentable, comment], class: 'comment-form hidden', id: "comment-form-#{commentable.class.name.underscore}-#{commentable.id}" do |f|
    div.comment-errors
      = render 'shared/errors', resource: comment
    .field.form-group
      = f.label :body
      = f.text_field :body, class: 'form-control'
    = f.submit 'Comment', class: 'btn btn-primary'
  

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.slim
#flash_messages.m-3
  - flash.each do |key, message|
    = content_tag :div, message, class: "flash-#{key}"

app/views/shared/_link_fields.html.slim
.nested-fields.link-fields
  .field.form-group
    = f.label :name, 'Link name'
    = f.text_field :name, class: 'form-control'
  .field.form-group
    = f.label :url
    = f.text_field :url, class: 'form-control'
  = link_to_remove_association "Remove link", f, class: 'btn btn-warning m-2'

app/views/shared/_links.html.slim
- unless links.empty?
  h5 Links:
  ul.links.list-group.m-2
    - links.each do |link|
      - cache [current_user || 'guest', link] do
        li.list-group-item id="link-#{link.id}"
          -if link.gist?
            -link.gist.each do |file|
              p= file[:name]
              code= file[:content]
          -else
            =link_to link.name, link.url

app/views/shared/_links_form.html.slim
h5 Links:
.links
  = form.fields_for :links do |f|
    = render 'shared/link_fields', f: f
  .add_link
    = link_to_add_association 'Add link', form, :links, partial: 'shared/link_fields', class: 'btn btn-secondary m-2'

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand.navbar-dark.bg-dark
  div.collapse.navbar-collapse
    ul.navbar-nav
      li.nav-item= link_to 'Questions', questions_path, class: 'nav-link'
      - if current_user
        li.nav-item= link_to 'Rewards', user_rewards_path(current_user), class: 'nav-link'
      - if can? :read, Search
        li.nav-item= link_to 'Search', search_path, class: 'nav-link'
      - if current_user
        li.nav-item= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'