config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  resource :authorization, only: %i[new create] do
    get 'email_confirmation/:confirmation_token', action: :email_confirmation, as: :email_confirmation
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :users do
    resources :rewards, only: %i[index]
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      member do
        post :best
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show destroy create update] do
        resources :answers, shallow: true, only: %i[index show destroy create update]
      end
    end
  end

  get 'search', controller: :search, action: :find, as: :search
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  include Linkable

  belongs_to :question, touch: true
  belongs_to :user
  has_one :reward

  has_many_attached :files

  validates :body, presence: true

  after_create :subscription_job

  def best!
    return if best

    Answer.transaction do
      Answer.where(question_id: question_id, best: true).update_all(best: false)
      update!(best: true)
      update!(reward: question.reward) if question.reward
    end
  end

  private

  def subscription_job
    QuestionSubscriptionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  after_action :publish_answer, only: :create

  helper_method :question

  expose :answers, from: :question
  expose :answer, scope: -> { Answer.with_attached_files }
  expose :comment, -> { answer.comments.new }

  def create
    authorize! :create, Answer
    question.answers << answer
    answer.user = current_user
    answer.save
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def update
    authorize! :update, answer
    answer.update(answer_params)
  end

  def best
    authorize! :best, answer
    answer.best!
  end

  private

  def publish_answer
    return if answer.errors.any?

    AnswersChannel.broadcast_to(
      answer.question,
      answer: answer,
      links: answer.links,
      files: answer.files.map { |file| { id: file.id, name: file.filename.to_s, url: url_for(file) } }
    )
  end

  def question
    Question.find_by(id: params[:question_id]) || answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  expose :answers, from: :question
  expose :answer, scope: -> { Answer.with_attached_files }

  def index
    authorize! :index, Answer
    render json: answers, each_serializer: BaseAnswerSerializer
  end

  def show
    authorize! :read, answer
    render json: answer
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def create
    authorize! :create, Answer
    answer.user = current_resource_owner
    answer.question = question
    answer.save ? head(:ok) : head(422)
  end

  def update
    authorize! :update, answer
    answer.update(answer_params) ? head(:ok) : head(422)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def question
    Question.find_by(id: params[:question_id]) || answer.question
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache [current_user || 'guest', answer] do
  div.answer.card.p-3 id='answer-#{answer.id}'

    .card-body
      .btn-group.float-right.btn-group-sm
        -if can? :destroy, answer
          = link_to 'Delete answer', answer, remote: true, method: :delete, class: 'btn btn-danger'
        -if can? :update, answer
          = link_to 'Edit', '#', class: 'edit-answer-link btn btn-secondary', data: { answer_id: answer.id }
        -if !answer.best? && can?(:best, answer)
          =link_to 'Best', best_answer_path(answer), method: :post, remote: true, class: 'btn btn-primary'
        -if can? :vote_up, answer
          = link_to 'Vote up', vote_up_answer_path(answer), class: 'votes vote-up btn btn-secondary', method: :post, remote: true
        .votes-count.btn.btn-success.disabled= answer.rating
        -if can? :vote_down, answer
          = link_to 'Vote down', vote_down_answer_path(answer), class: 'votes vote-down btn btn-secondary', method: :post, remote: true

      p= answer.body

    - if answer.files.attached?
      = render 'shared/attachments', attachments: answer.files, resource: answer

    = render 'shared/links', links: answer.links

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      div.answer-errors
        = render 'shared/errors', resource: answer
      .field
        = f.label :body
        = f.text_area :body
      .field
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
      = render 'shared/links_form', form: f
      = f.submit 'Save'
    = render 'shared/comments', commentable: answer

app/views/answers/_form.html.slim
= form_with model: [question, answer], class: 'new-answer' do |f|
  h5 Answer the question:
  div.answer-errors
    = render 'shared/errors', resource: answer
  .field.form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  .field.form-group
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'
  = render 'shared/links_form', form: f
  = f.submit 'Answer the question', class: 'btn btn-primary'

app/views/answers/best.js.erb
<% if answer.best? %>
  $('.answers').html('<%= j render question.answers %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<%- if answer.persisted? %>
  $('.answers').append('<%= j render answer %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer input[type=text]').val('');
<% end %>

app/views/answers/destroy.js.erb
<%- unless answer.persisted? %>
  $('#answer-<%= answer.id %>').remove()
<% end %>

app/views/answers/new.html.slim
= form_with model: [question, answer], class: 'new-answer' do |f|
  div.answer-errors
    = render 'shared/errors', resource: answer
  = f.label :body
  = f.text_area :body
  = f.submit 'Answer the question'
  = render 'shared/links_form', form: f
  

app/views/answers/update.js.erb
$('#answer-<%=answer.id%> .answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<%- unless answer.errors.present? %>
  $('#answer-<%=answer.id%>').replaceWith('<%= j render answer %>');
<% end %>