config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  resource :authorization, only: %i[new create] do
    get 'email_confirmation/:confirmation_token', action: :email_confirmation, as: :email_confirmation
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :users do
    resources :rewards, only: %i[index]
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      member do
        post :best
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show destroy create update] do
        resources :answers, shallow: true, only: %i[index show destroy create update]
      end
    end
  end

  get 'search', controller: :search, action: :find, as: :search
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question, touch: true

  validates :question, uniqueness: { scope: :user_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  expose :subscription, build_params: -> { { question_id: params[:question_id], user_id: current_user&.id } }

  helper_method :question

  def create
    authorize! :create, Subscription
    subscription.save
  end

  def destroy
    authorize! :destroy, subscription
    subscription.destroy
  end

  private

  def question
    Question.find_by(id: params[:question_id]) || subscription.question
  end
end

app/views/subscriptions/_subscription.html.slim
- if current_user.subscribed?(question)
  = link_to('Unsubscribe', subscription_path(current_user.subscription(question)), method: :delete, remote: true, class: 'subscription btn btn-secondary')
- else
  = link_to('Subscribe', question_subscriptions_path(question), method: :post, remote: true, class: 'subscription btn btn-primary')

app/views/subscriptions/create.js.erb
$('#question-<%=question.id%> .subscription').replaceWith('<%= render 'subscription' %>')

app/views/subscriptions/destroy.js.erb
$('#question-<%=question.id%> .subscription').replaceWith('<%= render 'subscription' %>')